--그룹 함수
--**일반 컬럼과 같이 사용이 불가능하다.**


--SUM : 합
--AVG : 평균
--COUNT : 총 개수
--MAX : 최대값
--MIN : 최소값


SELECT ENAME, COMM FROM EMP WHERE COMM IS NOT NULL;
SELECT SUM(COMM) "커미션 총합" FROM EMP WHERE COMM IS NOT NULL;
SELECT SUM(COMM) "커미션 총합" FROM EMP;
SELECT * FROM EMP;

SELECT MAX(SAL) FROM emp;
SELECT MIN(SAL) FROM emp;
SELECT ROUND(AVG(SAL),2) FROM emp;  --반올림

SELECT COMM FROM EMP;
SELECT COUNT(*), COUNT(COMM) FROM EMP;    --NULL은 집계 X      결과 : 4

SELECT COUNT(DISTINCT JOB) FROM EMP;    -- JOB 에 대하여 중복 제거 후 COUNT
--                                                결과 : 6

-- GROUP BY : 그룹 함수를 어떤 컬럼 값을 기준으로 그룹 함수를 적용할 경우에 쓴다.
--SELECT 컬럼명, 그룹함수
--FROM 테이블명
--WHERE 조건
--GROUP BY 컬럼명;
--의 형식으로 사용 함.

SELECT DEPTNO FROM EMP GROUP BY DEPTNO;        --DEPTNO를 기준으로 그룹생성
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO ASC ;
SELECT DEPTNO, ENAME, SAL FROM EMP ORDER BY DEPTNO ASC;

SELECT JOB, SUM(SAL) FROM EMP GROUP BY JOB;
SELECT JOB, SUM(SAL) FROM EMP GROUP BY JOB ORDER BY SUM(SAL) DESC;

SELECT * FROM EMP;
-- HAVING >>>>>>>>>> GROUP BY 조건절
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) >= 500;
-->> DEPTNO 기준으로 그룹을 나눠 나온 결과중 HAVING 조건에 해당하는 내용만 출력 
--** 시점이 중요함
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, AVG(SAL) FROM EMP WHERE SAL > 300 GROUP BY DEPTNO;
-->>>> SAL 이 300 초과하는 범위에서 DEPTNO 그룹화 후 결과출력
SELECT DEPTNO, MAX(SAL), MIN(SAL) FROM EMP GROUP BY DEPTNO 
HAVING MAX(SAL) <= 500;




