--SEQUENCE >>>>>>>>>>>>>> 자동 번호 생성 ??? (유일)


--형식
--CREATE SEQUENCE Update_sequence
-- START WITH 10 INCREMENT BY 10;


-- START WITH : 시작값
-- INCREMENT WITH : 증가하는 정도

-- 기본값은 1에서부터 1씩 증가한다.

CREATE SEQUENCE DEPT_DEPTNO_SEQ
INCREMENT BY 10 START WITH 10;




SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG 
FROM USER_SEQUENCES;

--시퀀스의 현재 값 반환 : CURRVAL
--시퀀스의 다음 값 반환 : NEXTVAL


SELECT DEPT_DEPTNO_SEQ.NEXTVAL FROM DUAL;

SELECT DEPT_DEPTNO_SEQ.CURRVAL FROM DUAL;

CREATE SEQUENCE EMP_SEQ
INCREMENT BY 1 START WITH 1
MAXVALUE 100000;

CREATE TABLE EMP01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    HIREDATE DATE
    );
   
INSERT INTO EMP01
VALUES(EMP_SEQ.NEXTVAL, '김씨', SYSDATE);

SELECT * FROM EMP01;


CREATE TABLE DEPT_EXAMPLE(
    DEPTNO NUMBER(4) PRIMARY KEY,
    DNAME VARCHAR2(15),
    LOC VARCHAR2(15)
    );

SELECT * FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'DEPT_EXAMPLE';

CREATE SEQUENCE DEPT_EXAMPLE_SEQ
INCREMENT BY 10 START WITH 10
MAXVALUE 100000;


INSERT INTO DEPT_EXAMPLE
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '경리부', '서울');
INSERT INTO DEPT_EXAMPLE
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '인사부', '인천');
INSERT INTO DEPT_EXAMPLE
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '영업부', '용인');
INSERT INTO DEPT_EXAMPLE
VALUES(DEPT_EXAMPLE_SEQ.NEXTVAL, '전산부', '수원');





--위와 같이 보통 INSERT문과 함께 쓰임.
-- 시퀀스명.NEXTVAL

SELECT * FROM DEPT_EXAMPLE;