SELECT * FROM EMP;
-- 기본 형태
-- SELECT ( 조회할 COLUMN들 ) FROM ( 조회할 테이블 명 );


SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL <= 500;
-- WHERE 뒤에 조건을 붙여서 원하는 데이터를 추출할 수 있음

SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME = '오지호';
SELECT * FROM EMP WHERE ENAME = '오지호';
-- 문자열 일치 조건도 가능

--IN ( A,B,C ) >>>>>> OR를 묶을 수 있음.
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL = 250 OR SAL = 300 OR SAL = 500;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL IN (250, 300, 500);
-- OR AND와 같은 비교연산자 또한 사용 가능

--아래 두 코드는 똑같은 역할을 한다.
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL != 250 AND SAL != 300 AND SAL !=500;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL NOT IN( 250,300,500);

-- NULL의 경우  A = NULL 과 같이 사용 불가능 = 대신 IS 를 사용한다.
SELECT * FROM EMP WHERE MGR IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;

SELECT EMPNO,ENAME, JOB, HIREDATE FROM EMP ORDER BY HIREDATE DESC;
-- ORDER BY 를 활용해 특정 칼럼을 정렬하여 출력할 수 있음


SELECT DEPTNO, EMPNO, ENAME, JOB, HIREDATE FROM EMP ORDER BY DEPTNO ASC, 
HIREDATE ASC;
-- DEPTNO 먼저 정렬 후 같은 경우에 HIREDATE를 기준으로 정렬한다.

SELECT
    * FROM EMP WHERE HIREDATE > '04/01/01';
    
SELECT EMPNO,ENAME, SAL FROM EMP WHERE SAL BETWEEN 300 AND 500;
-- BETWEEN >>>>>>>>300 이상 500 이하

SELECT * FROM DEPT;

SELECT ENAME, SAL FROM EMP WHERE DEPTNO = 20 ORDER BY SAL DESC;
-- FROM / WHERE / ORDER BY >> 기본값은 ASC 이다.





